# Generated by Django 4.2.5 on 2024-02-15 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 21, 48, 51, 392060, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 21, 48, 51, 392060, tzinfo=datetime.timezone.utc), verbose_name='Дата расчета'),
        ),
    ]
