# Generated by Django 4.2.7 on 2023-12-19 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartment",
                    models.IntegerField(default=255, verbose_name="Номер квартиры"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Введён"),
                            (2, "В работе"),
                            (3, "Завершён"),
                            (4, "Отменён"),
                            (5, "Удалён"),
                        ],
                        default=1,
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date_estimate",
                    models.DateField(
                        default=datetime.date(2023, 12, 19), verbose_name="Дата расчета"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            19,
                            20,
                            52,
                            15,
                            482823,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "date_of_formation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата формирования"
                    ),
                ),
                (
                    "date_complete",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="moderator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассчет",
                "verbose_name_plural": "Рассчеты",
                "ordering": ("-date_of_formation",),
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(default="Описание", verbose_name="Описание"),
                ),
                ("type", models.CharField(verbose_name="Единица измерения")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Действует"), (2, "Удалена")],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="indicators/default.jpg",
                        upload_to="",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показатель",
                "verbose_name_plural": "Показатели",
            },
        ),
        migrations.CreateModel(
            name="IndicatorEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FloatField(default=1000, verbose_name="Значение счётчика"),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculation.estimate",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculation.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показатель-Расчет",
                "verbose_name_plural": "Показатели-Расчеты",
            },
        ),
    ]
