# Generated by Django 4.2.5 on 2023-11-19 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Электроэнергия', max_length=100, verbose_name='Название')),
                ('description', models.TextField(default='Описание', max_length=500, verbose_name='Описание')),
                ('type', models.CharField(default='кВт.ч', verbose_name='Единица измерения')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(default='indicators/default.jpg', upload_to='indicators', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=10, verbose_name='Количество')),
                ('apartment', models.IntegerField(default=255, verbose_name='Номер квартиры')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 11, 19, 11, 42, 30, 788011, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 11, 19, 11, 42, 30, 788011, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 11, 19, 11, 42, 30, 788011, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('indicators', models.ManyToManyField(null=True, to='calculation.indicator', verbose_name='Показатели')),
            ],
            options={
                'verbose_name': 'Рассчет',
                'verbose_name_plural': 'Рассчеты',
            },
        ),
    ]
