# Generated by Django 4.2.4 on 2023-11-08 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=10, verbose_name='Количество')),
                ('apartment', models.IntegerField(default=255, verbose_name='Номер квартиры')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 11, 8, 9, 36, 52, 314669, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 11, 8, 9, 36, 52, 314669, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 11, 8, 9, 36, 52, 314669, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Рассчет',
                'verbose_name_plural': 'Рассчеты',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Электроэнергия', max_length=100, verbose_name='Имя')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('description', models.TextField(default='Описание', max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(default='indicators/default.jpg', upload_to='indicators', verbose_name='Фото')),
                ('type', models.CharField(default='кВт.ч', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
    ]
