# Generated by Django 4.2.7 on 2023-11-20 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 16, 17, 24, 61957, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 16, 17, 24, 61751, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 16, 17, 24, 61951, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
